---

# File for task "Configure Elasticsearch"
#

- name: Configure Elasticsearch
  become: true
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart Elasticsearch
