---
# Files for task "Download Elasticsearch's rpm"
#

- name: "Download Elasticsearch's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
    dest: "/tmp/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
  register: download_elastic
  until: download_elastic is succeeded
